sudo: required
dist: trusty  
language: csharp
solution: TS3QueryLib.Net.Core.sln
mono: none
dotnet: 1.0.4

branches:  
  only:
    - master
    
script:
  - dotnet restore
  - dotnet build -c Release -v normal TS3QueryLib.Net.Core/TS3QueryLib.Net.Core.csproj
